# Use root/example as user/password credentials
version: '3.1'

services:

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: employee_db
        ports:
            - 5432:5432