# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: department_db
      MYSQL_USER: igor
      MYSQL_PASSWORD: Mudar@1234
    ports:
      - 3306:3306
